### ISSUE TITLE
Allow manual mapping

### ISSUE THREAD

**Issue by ssoulless** [pcreux/csv-importer#102]
Right now all the mapping occurs programmatically, what if I want the users to manually select the mapping in the UI?

I would need to send a hash with the configuration, however, I cannot find a proper way of setting up the mapping in this scenario with this gem.

**Comment by ssoulless** [comment]
I think this could be achieved with header transformations feature

**Comment by pcreux** [comment]
Hello,

You should be able to [define the configuration at runtime](https://github.com/pcreux/csv-importer#overwrite-configuration-at-runtime). Ex:

```ruby
params = { email_col: "email_2", name: "first_name" }

email_column = params[:email_col]
name_column = params[:name_col]

import = ImportUserCSV.new(file: my_file) do
  column :email, to: email_column
  column :name, to: name_column
end
```
