### ISSUE TITLE
Adding an error to a row from a to: block?

### ISSUE THREAD

**Issue by unikitty37** [pcreux/csv-importer#103]
I'm importing a CSV which contains a `Scheme ID` column, which contains the `id` for the Scheme that has an `external_reference` matching the value in the column (so customers can use their own references rather than our own internal IDs).

However, if there is not a Scheme with a matching `external_reference`, the row should be marked as invalid. I can't see anything in the README which tells me how to do this.

This is what I have so far — but what do I replace the `???` with in order to cause the row to be marked invalid, preferably with my own error message? Do I just raise an exception?

```
column :scheme_id, required: true, as: ['Scheme ID'], to: -> (scheme_id, ticket) do
  schemes = Scheme.where(external_reference: scheme_id)
  ??? if schemes.empty? 
  ticket.scheme_id = schemes.first.id
end
```

**Comment by unikitty37** [comment]
Thanks — unfortunately, this doesn't work for all columns.

When creating a Ticket normally, it's valid to have `scheme_id` be `nil`. However, when importing from the CSV, we allow an empty field to set it to `nil`, but a mismatching reference should cause the row to be marked invalid.

This doesn't seem to add the error to the ticket, though, and Rails still thinks it is valid.

```ruby
    column :scheme_id, required: true, as: ['Scheme ID'], to: lambda { |scheme_id, ticket|
      unless scheme_id.blank?
        ticket.scheme_id = Scheme.where(external_reference: scheme_id).pluck(:id).first

        if ticket.scheme_id.nil? && !scheme_id.blank?
          ticket.errors.add(:scheme_id, 'does not match any existing scheme')
      end
    }
```

The only way I can think of handling these validations would be to add a `imported_from_csv` to Ticket, and set those extra validations to only run when `imported_from_csv` is true. But this seems a very messy way of doing it.

**Comment by pcreux** [comment]
One option would be to add an instance variable to `Ticket` then.

```ruby
  column :scheme_external_identifier, required: true, as: 'Sheme ID'
```

```ruby
class Ticket
  attr_accessor :scheme_external_reference

  before_validation :set_scheme_id_from_external_reference
  validates :validate_scheme_external_reference

  private

  def set_scheme_id_from_external_reference
    return if external_reference.blank?

    self.scheme_id = Scheme.where(external_reference: scheme_external_reference).pluck(:id).first
  end

  def validate_scheme_external_reference
    errors.add(:scheme_external_reference, :invalid) if scheme_external_reference.present? && scheme_id.nil?
  end
end
```

Some might not like adding this logic to the ActiveRecord model though. :)
