### ISSUE TITLE
skip! does not indicate which row was skipped in the report

### ISSUE THREAD

**Issue by unikitty37** [pcreux/csv-importer#105]
When I use `skip!` in `after_build`, the summary shows `1 records create skipped`, and the report shows as empty. This means that there's no way of telling the end-user *which* rows were skipped, much less why.

Would it be possible for `skip!` to take an optional string parameter, giving the reason for skipping a row, and for the report to show as

```
{ "2" => { :skipped => nil } }
```

if `skip!` is called on row 2, or

```
{ "2" => { :skipped =>"some reason" } }
```

if `skip! 'some reason'` is called on row 2?

**Comment by pcreux** [comment]
You should be able to know which row where skipped via `report.create_skipped_rows` and `report.update_skipped_rows`. 

https://github.com/pcreux/csv-importer/blob/97ec55448ab8720e3976d9f385a9e196e2b6ecf3/lib/csv_importer/report.rb#L24-L25

Adding a reason would be an interesting addition. PRs are welcomed. :)
