### ISSUE TITLE
Encodings

### ISSUE THREAD

**Issue by keferboeck** [pcreux/csv-importer#110]
Is there a list with all available encodings available? I tried UTF-16BE and ISO Western (ISO-8859-1) to account for German Umlaute and special characters. I get either a message that the encoding doesn't exist, or it is being ignored as the all Umlaute are removed in the export - 

Example: 

`import = StammdatenArtikelExporter.new(path: File.join(Rails.root, 'app', 'csv', 'artikel-neu-5-short.csv'), enc
oding: 'UTF-8mb4')`

Thank you for your help! Btw. Awesome Gem :D

**Comment by pcreux** [comment]
> Is there a list with all available encodings available?

It looks like you can get the list using this method: https://docs.ruby-lang.org/en/3.0/Encoding.html#method-c-name_list

> all Umlaute are removed in the export

They might be removed when reading the file (because of encoding) or when importing the data in the database depending on the encoding used by the database.

Good luck! :)
