### ISSUE TITLE
Pass Column as parameter in "to" procs

### ISSUE THREAD

**Issue by fxgallego** [pcreux/csv-importer#48]
I'd like to add a 3rd option to this case where the block passed uses the column (not column_definition) too. This allows to do custom conversion with metadata stored in the column name. For example the columns header is defined as "name, birthdate[%d/%m/%y], address". So the column name matches trough a regex and you can capture the metadata inside []

```
    case to_proc.arity
    when 1 # to: ->(email) { email.downcase }
      model.public_send("#{column_definition.name}=", to_proc.call(csv_value))
    when 2 # to: ->(published, post) { post.published_at = Time.now if published == "true" }
      to_proc.call(csv_value, model)
   when 3 [some code]
    else
      raise ArgumentError, "`to` proc can only have 1 or 2 arguments"
```

**Comment by fxgallego** [comment]
Please see the implementation proposal https://github.com/fxgallego/csv-importer/commit/e524507d67429a551f293228e41a50960574722d

**Comment by pcreux** [comment]
I'll review this later this week. I came across the same issue a while back. :)

**Comment by fxgallego** [comment]
Thanks!

**Comment by pcreux** [comment]
Closed by https://github.com/pcreux/csv-importer/pull/73 thanks to @stas !
