### ISSUE TITLE
Empty Row Column at beginning of csv gives an error.

### ISSUE THREAD

**Issue by aromaron** [pcreux/csv-importer#54]
When ever I have a file like in the image below, with an empty row above the headers and a empty column before the first one it breaks the importer with an error. i.e I get a 'email column is missing' is this a known issue? or am I missing something?

![csv_example](https://cloud.githubusercontent.com/assets/585208/20933257/1f79b0ac-bb9d-11e6-8df6-255f3e166503.png)

**Comment by pcreux** [comment]
Hey @aromaron! I believe that you're not *missing* something, you have an *extra* row and and *extra* column. CSVImporter assumes that the header is defined in the first row. Please remove the blank row before passing the content to CSVImporter.
