### ISSUE TITLE
Postgresql Array format

### ISSUE THREAD

**Issue by zambra** [pcreux/csv-importer#56]
Hi,
I'm using an array of integers but csv-importer fails silently in this case. Here is an example sensor.csv with a name, date and an array of temperatures
`sensor01,2017-01-28,14 17 19`

Is there a way to specify that the last field is an array? 

Edit: I know that I can reformat the csv file to something like 
`sensor01,2017-01-28,"{14, 17, 19}"`
but maybe there's a clever way to do it in the class without modifing the csv file

**Comment by pcreux** [comment]
Indeed! Would the following work?

```
column :temperatures, to: ->(temperatures) { temperatures.split(" ") }
```

**Comment by zambra** [comment]
Thanks Philippe, it works perfectly  👍 
csv-importer is a real time saver

**Comment by pcreux** [comment]
Glad to hear! Thanks

φ
