### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by ACPK** [pcreux/csv-importer#57]
Whenever I try to use this feature, I get timeouts on production.  Any suggestions on moving this to a background job (we're using AWS SQS)?

**Comment by pcreux** [comment]
You just need to store the content of your CSV file somewhere (AWS S3?) to run the job in the background. I believe you would push a message to AWS SQS with the uri of that file and any other information you need to process it (user, account ....).

**Comment by ACPK** [comment]
@pcreux - And then keep checking the status of the background job to get the progress?

**Comment by pcreux** [comment]
`url:` is not a valid option. Get the content of the file first and pass it to via `content`. See https://github.com/pcreux/csv-importer#import-from-a-file-path-or-string.
