### ISSUE TITLE
Errno::ENOENT (No such file or directory @ rb_sysopen" ... )

### ISSUE THREAD

**Issue by ACPK** [pcreux/csv-importer#58]
When I pass in the url S3 url, I get "No such file or directory @ rb_sysopen". Does the "path" not accept a full S3 url?

**Comment by pcreux** [comment]
It does not indeed. Load the content of the file in a string first and pass it down via `content`.

**Comment by ACPK** [comment]
@pcreux Why does it not accept a path?

**Comment by pcreux** [comment]
@ACPK Loading the content from a url is not trivial and I'd rather let the user implement it. Unfortunately, CSVImporter loads the whole CSV file before running the import. It might not be a good fit for CSVs for 100k+ in its current form.

PRs are welcomed! :)
