### ISSUE TITLE
Get current_user into CSVImporter::Row for after_build

### ISSUE THREAD

**Issue by adambedford** [pcreux/csv-importer#60]
Is there a good way to get `current_user` into the context for an `after_build` or `after_save`?

**Comment by pcreux** [comment]
You should be able to by defining the after_build "at runtime". See
https://github.com/pcreux/csv-importer/blob/master/README.md#after_build-and-after_save-callbacks

**Comment by adambedford** [comment]
Hi Phillippe, Thanks for your response. 

I am defining the after_build at runtime, however I'm running into this error:

`undefined local variable or method `current_user' for #<CSVImporter::Row:0x007fc309d5e5e8>`

as it seems the `after_build` is evaluated in the context of a `Row`.

Here's the importer, defined in a service object that has a `current_user` method:

```ruby
def importer
  @_importer ||= UserImporter.new(file: file) do
    after_build do |user|
      user.invited_by = current_user

      if skip_invitation?
        user.skip_invitation = true
        schedule_invitations(user)
      end
    end
  end
end
```

Any thoughts? Looking through the code it doesn't look like there's anywhere to pass in any additional context to the `Configurator`

**Comment by pcreux** [comment]
This is bug then. Those block should be evaluated in the context of the
caller. I can look into that within the next 2 weeks.

**Comment by pcreux** [comment]
Hey @adambedford ! Ok, I found what the issue is. The `after_build` and `after_save` blocks are ran using `instance_exec` which provide them with access to variables, not methods.

As a work around, you could do the following:

```
def importer
  @_importer ||= begin
  _current_user = current_user
  _skip_invitation = skip_invitation?

  UserImporter.new(file: file) do
    after_build do |user|
      user.invited_by = _current_user

      if _skip_invitation
        user.skip_invitation = true
        MyService.schedule_invitations(user)
      end
    end
  end
end
end
```

Now... I let you find a better way to do this. :)

**Comment by adambedford** [comment]
Thanks Philippe! I hadn't spotted that nuance.
