### ISSUE TITLE
Upload file 

### ISSUE THREAD

**Issue by saroar** [pcreux/csv-importer#64]
Can I upload only CSV file in director and save it in my rails app if yes how I can only upload?

**Comment by pcreux** [comment]
Hey there! I'm not sure to understand what `director` is. :)

**Comment by saroar** [comment]
i mean when we upload the image it saves in rails public folder i need something same features want to save csv file in my rails folder how I can do it? is it possible with you gem?

**Comment by pcreux** [comment]
Hey there. It's definitely doable with rails to upload any type of files.

csv-importer takes care of importing the CSV file that's been uploaded to
the database. It doesn't seem to be what you're looking for.

**Comment by saroar** [comment]
thanks bro for your answer do know any gem or very simple code where i can upload only CSV file not else and not more than 1mb 
or if u know some code it will be great for me I will like to create one simple gem

**Comment by pcreux** [comment]
That's a good start:
https://stackoverflow.com/questions/14174044/uploading-a-file-in-rails
