### ISSUE TITLE
Ruby 2.7.1 - ArgumentError: unknown encoding name - UTF-8:UTF-8

### ISSUE THREAD

**Issue by scottbarrow** [pcreux/csv-importer#92]
Hey Philippe
Ruby 2.7.1 is creating an exception on calling header
`ArgumentError: unknown encoding name - UTF-8:UTF-8` with the default encoding. 
set here https://github.com/pcreux/csv-importer/blob/a63e180830bb7a36e2b9b9a377843a3d72ad02e6/lib/csv_importer/csv_reader.rb#L11
Passing `encoding: 'UTF-8'` to the initializer is a workaround

also, csv-importer-0.7.0/lib/csv_importer/csv_reader.rb:49: warning: Using the last argument as keyword parameters is deprecated (kwargs change in 2.7)

**Comment by pcreux** [comment]
Thank you for reporting that. I'm not sure when I'll get a chance to look into it. Let be know if it's blocking you. PRs are always welcome. 🙃

**Comment by pcreux** [comment]
Fixed by #93
