### ISSUE TITLE
Rails 6.1 errors hash deprecation warning

### ISSUE THREAD

**Issue by stevenou** [pcreux/csv-importer#98]
Hello, thanks for the awesome gem! Just started playing with it and it saves so much time compared to past experiences with CSV imports. 

The following warning triggers in `row.rb#78` with Rails 6.1.2.1. Easy enough to fix for Rails 6.1+ but if backwards compatibility needs to be maintained, I'm not sure what's the cleanest way to do that. What do you think? Thanks!

```
DEPRECATION WARNING: Enumerating ActiveModel::Errors as a hash has been deprecated.
In Rails 6.1, `errors` is an array of Error objects,
therefore it should be accessed by a block with a single block
parameter like this:

person.errors.each do |error|
  attribute = error.attribute
  message = error.message
end

You are passing a block expecting two parameters,
so the old hash behavior is simulated. As this is deprecated,
this will result in an ArgumentError in Rails 6.2.
```

**Comment by pcreux** [comment]
Hey @stevenou , I'm glad that this gem is saving you some time!

Thank you for reporting this. I believe that it's coming from:

https://github.com/pcreux/csv-importer/blob/26d66cb5728519a90dc3a7147504d276f8bd0b13/lib/csv_importer/row.rb#L80

I'm wondering if this API (`errors.each do |error|`) is compatible with Rails 4+ or if there's something like `errors.to_h`.

PRs are welcomed. ;)

**Comment by stevenou** [comment]
Ok, so it would appear that `csv-importer` currently actually only returns the _last_ error for each attribute, not _all_ errors for each attribute. That's because the `Hash[]` here will only retain the last error if there are multiple entries with the same key (`column_name`/`attribute`) 

https://github.com/pcreux/csv-importer/blob/26d66cb5728519a90dc3a7147504d276f8bd0b13/lib/csv_importer/row.rb#L79-L87

Ideally, we might want to change the value in the resulting hash to be an array, rather a string, so it can hold _all_ errors for a given attribute. However, that is probably a breaking change. 

So I'll just submit a PR to remove the deprecation warning but keep the existing behavior. We can discuss the breaking change separately.

**Comment by pcreux** [comment]
You're 100% right. I'm not convinced that only keeping the last error was intentional. Let's merge your PR in for the `0.8.1` version. I believe that we could then release `0.9.0` where `errors` would return a hash where values would be array of errors.

**Comment by stevenou** [comment]
May I suggest making that 1.0.0 as that would be a breaking change?
